{% set name = "simple-dftd3" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/awvwgk/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 47b2614c911085690075dda5af70391c93d9a43fe067eae15bb6db72eac33aab

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('simple-dftd3', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - meson
    - ninja
    - asciidoctor
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  host:
    - libblas
    - mctc-lib
  run:
    - mctc-lib

test:
  commands:
    - s-dftd3 --version

about:
  home: https://github.com/awvwgk/simple-dftd3
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: Simple reimplementation of the DFT-D3 model
  doc_url: https://awvwgk.github.io/simple-dftd3/

extra:
  recipe-maintainers:
    - awvwgk
